### ISSUE TITLE
Consideration for role="presentation" on iframes

### ISSUE THREAD

**Issue by drewnielson** [atbcb/ICTTestingBaseline#239]
When role="presentation" is applied to an iframe, it removes the iframe as a target element and from the accessibility tree. While the iframe structure itself is removed from the accessibility tree, is child component information still reliably available? If it is not a target element and its structural semantics are removed from the accessibility tree, does it still require an accessible name/description?

Suggest we reconsider absolute requirement for accessible name/description when the iframe itself is not intended as a target element, and the content within the iframe is intended to appear and function as seamless content within the parent page.

Ex: [Google's reCAPTHCA in iframes](https://beta-staging.regulations.gov/comment/ERULE-2017-0074-0001) (scroll to the bottom of the page)

**Comment by kengdoj** [comment]
`Role="none"` should be included in whatever update is made for `role="presentation"`.

According to [Using ARIA](https://www.w3.org/TR/using-aria/#presentation), 
> For elements with no required children, any elements nested inside the element with role=presentation/none preserve their semantics.

But, more to consider with  [Fourth Rule of Aria](https://www.w3.org/TR/using-aria/#4thrule) -
> Do not use role="presentation" or aria-hidden="true" on a focusable element. Using either of these on a focusable element will result in some users focusing on 'nothing'.
- iFrame is focusable in some browsers. 
- Aria-hidden="true" would remove the iframe and content from the accessibility tree so shouldn't be acceptable if the iframe has visible content. 



We can borrow from [WebAim](https://webaim.org/techniques/frames/#iframe) to determine when iframe needs a title, but it's very subjective :

> Unlike frames, a descriptive title attribute value is not necessary for accessibility. If the inline frame presents content as a whole that is visually distinctive, such as an advertisement or video player, then a title should be provided to indicate this distinction.

**Comment by drewnielson** [comment]
OK, so the real question for me was whether adding `role="presentation"` had any effect on whether a browser would send focus to the iframe element itself. After some quick testing, looks like Firefox still gives the iframe a tab stop regardless of role. Suggest we leave the Baseline test as is and close this issue. @kengdoj, if you concur, we can close.

**Comment by kengdoj** [comment]
How about adding to the iframes test (borrowing from the meaningful images test steps 3,4,5):

3. If the iframe is focusable, check that

- Check that the ARIA role is NOT “presentation”.
- Check that the ARIA role is NOT “none”.
- Check that aria-hidden is NOT set to “true”.

4. If the iframe has visible content, check that aria-hidden is NOT set to “true”.

**Comment by drewnielson** [comment]
OK, yes. I can get behind that. But I think we need to somehow get around the ambiguity of browser treatment for iframe focus -  perhaps we also modify the Identify Content to limit the test to "iFrames that are not explicitly excluded from the tab order." Then again, there might be legitimate reasons for explicitly excluding iframes from the tab order, but the content of which should still be available to AT users, in which case aria-hidden="true" would be bad. So maybe we simply adjust the wording in each check. Something like:

1. If the `<iframe>` has visible content, check that aria-hidden is NOT set to “true”.
2. If the `<iframe>` is not explicitly excluded from the focus order (e.g., `tabindex="-1"`), check that the combination of the accessible name and accessible description is not empty.
3. If the `<iframe>` is not explicitly excluded from the focus order, check that the non-empty combination of accessible name and description for each `<iframe>` describes its content.
4. If the `<iframe>` is not explicitly excluded from the focus order, check that:
    * Check that the ARIA role is NOT “presentation”.
    * Check that the ARIA role is NOT “none”.
    * Check** that aria-hidden is NOT set to “true”.

**Comment by kengdoj** [comment]
> we need to somehow get around the ambiguity of browser treatment for iframe focus

I can see using this programmatic approach to achieve consistency in test results across browsers, but I don't think we need this in the Baseline. (For TT exam, yes). The test is applicable when an iframe is focusable, regardless of the reason why it is (or isn't) focusable. Maybe we can have 2 tests for iframes:

19.2 Focusable iframes
Identify content: iframes that are focusable

1. Check that the combination of the accessible name and accessible description is not empty.
2. Check that the non-empty combination of accessible name and description for each <iframe> describes its content
1. Check that the ARIA role is NOT “presentation”.
2. Check that the ARIA role is NOT “none”.
3. Check that aria-hidden is NOT set to “true”.

19.3 iframes with content
Identify content: iframes with visible content
1. Check that aria-hidden is NOT set to “true”.

**Comment by cliffbert** [comment]
19.3 iframes with content
Identify content: iframes with visible content
Probably most/all of the time, but should we specify visible *meaningful* content?

**Comment by kengdoj** [comment]
@cliffbert: that makes sense but the [ARIA 1.1 guidance for aria-hidden](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden) doesn't mention _meaningful_, just visible: 

> Note:
> Authors are advised to use extreme caution and consider a wide range of disabilities when hiding visibly rendered content from assistive technologies.

**Comment by cliffbert** [comment]
Seems incorrect to apply this test to non-meaningful (but visible) content ...?

**Comment by kengdoj** [comment]
Can we leave 19.3 out since this is not covered by 4.1.2?
