### ISSUE TITLE
Add Tests for SC 4.1.2 Role, Value

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#240]
Test needed for role, state, value part of this SC.

Edit: These are already included in [5. Changing Content](https://section508coordinators.github.io/ICTTestingBaseline/05Changing.html), but not in any other tests.

**Comment by kengdoj** [comment]
Group Discussion:
- test needed for name and role
- test for "states, properties, and values that can be set by the user can be programmatically set" needs more discussion. Would AT be required to test programmatically set?

**Comment by cliffbert** [comment]
Also we discussed the requirement to test after elements are updated. However, doesn't this imply that the user also needs to know name, role and state beforehand, so that they can decide whether or not to interact with and change name/role/state of the control?

**Comment by kengdoj** [comment]
Unresolved questions:
- How to test?
-- If testing _only explicit roles_ (`role=`), this misses elements that _should_ have a role assigned but do not
-- If testing _both explicit and implicit roles_, all elements have programmatic roles (including role=none)
- How will testers evaluate role correctness with roles that overlap (e.g., table/grid, button/link)? Very subjective testing.

Consider adding a Role Baseline Test or including a role test in other Baseline Tests later with answers to these and other questions.

**Comment by kengdoj** [comment]
Wording of SC 4.1.2 indicates not checking for the programmatic property, but **SETTING** it programmatically. Unsure how to test: 

> "states, properties, and values that can be set by the user **can be programmatically set**;"

**Comment by kengdoj** [comment]
Not this issue of testing 4.1.2, but for awareness - [ACT issue about testing the different states for conformance](https://github.com/act-rules/act-rules.github.io/issues/1511)

**Comment by kengdoj** [comment]
Related to #350

**Comment by kengdoj** [comment]
June 1, 2023 Discussion on adding a Test for Role: SSA, GSA, USAB, DHS

Add tests  to check _explicit roles_:

1. From [ARIA in HTML](https://www.w3.org/TR/html-aria/#avoid-overriding-interactive-elements-with-non-interactive-roles): 
  a.  interactive elements with non-interactive roles. Ex: `<button role="heading">search</button>`
  b. roles not to be used by authors: [List of Abstract Roles](https://www.w3.org/TR/wai-aria-1.2/#abstract_roles)

1. Add a test to check for a valid role ([ACT Rule: Role attribute has valid value](https://www.w3.org/WAI/standards-guidelines/act/rules/674b10/proposed/#wai-aria-specifications)) from these ARIA specs:

- [Accessible Rich Internet Applications (WAI-ARIA) 1.2](https://www.w3.org/TR/wai-aria-1.2/)
- [WAI-ARIA Graphics Module 1.0](https://www.w3.org/TR/graphics-aria-1.0/)
- [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria-1.0/)
