### ISSUE TITLE
12.2 Layout tables test 

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#284]
[12.2 Layout Tables](https://section508coordinators.github.io/ICTTestingBaseline/12DataTables.html#test-instructions-1) should include the "UNLESS..." conditions from b:
c.	Do NOT identify column or row headers using role="columnheader" or role="rowheader" in an ARIA grid (where the data grid is identified using role="grid") 

> UNLESS at least one of the following is true:
> a.	the table has role="presentation"
> b.	the table has role="none"

**Comment by kengdoj** [comment]
Also review "(where the data grid is identified using role="grid")." 
TT has deemed this not necessary because role="grid" can be used on data and layout tables.

**Comment by drewnielson** [comment]
It is precisely because grid can be used for data and layout tables that we need to specifically check for when grid is used in combination with data table structure elements/roles. TT does not specifically call out grid because ANDI will identify it as a table in the tables module whether it is a `<table>`, uses `role="table"`, or uses `role="grid"`.

**Comment by kengdoj** [comment]
Discussion:
- if checking for role="presentation" on role="grid", that's 2 roles on an element. What is spec for 2 roles?

**Comment by kengdoj** [comment]
ACTION: do some testing, find the spec to determine precedence when 2 roles are assigned.

**Comment by kengdoj** [comment]
From [Core Accessibility API Mappings 1.1](https://www.w3.org/TR/core-aam-1.1/#exclude_elements2):

> 5.1.1 Excluding Elements from the Accessibility Tree §
> The following elements are not exposed via the accessibility API and user agents MUST NOT include them in the accessibility tree:
> 
> Elements with none or presentation **_as the first mappable role in the role attribute_**.

**Comment by kengdoj** [comment]
See https://github.com/atbcb/ICTTestingBaseline/issues/285#issuecomment-929656567 - first supported role if more than 1 role assigned.

**Comment by drewnielson** [comment]
Recommend adding explanatory note regarding presentation role conflict resolution (explicit roles that do not inherit `role="presentation'` or `none`) under last paragraph of Test Method Rationale for 12 Tables.

**Comment by cliffbert** [comment]
Just to clarify: "Authors MUST ensure elements with role row are contained in, or owned by, an element with the role table, grid, rowgroup, or treegrid."
