### ISSUE TITLE
Add wording that placeholder would not meet 10.5 Label

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#328]
From [Understanding 3.3.2](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html)

- Content authors may also choose to make such instructions available to users only when the individual control has focus especially when instructions are long and verbose.
- The goal is to make certain that enough information is provided for the user to accomplish the task without undue confusion or navigation.

a label that disappears (like `placeholder`) would not meet 3.3.2

**Comment by kengdoj** [comment]
Suggest "The label or instruction must be visible while the form field has focus."

**Comment by cliffbert** [comment]
Note: TT for 1 3.3.2-label-provided has this note: "The label or instruction must be visible when the form field has focus."

**Comment by cliffbert** [comment]
Suggest "The label or instruction must remain visible while the form field has focus."

**Comment by kengdoj** [comment]
WG votes for "must be visible while".

**Comment by kengdoj** [comment]
Completed.

Preview: https://federalist-78ccea55-7a06-447c-aabf-bd620b207b74.app.cloud.gov/preview/atbcb/icttestingbaseline/nextupdateafter301/10Forms/#105-test-procedure-for-form-has-a-visible-label
