### ISSUE TITLE
10.5 Form has a label

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#335]
[10.5 Test Procedure for Form has a Label Test instruction](https://ictbaseline.access-board.gov/10Forms/#test-instructions-4), insert "visible" - 

> Check that each form component has ***visible*** label(s) or instructions. [SC 3.3.2]

Should 10.5's test be called "Form has a visible label"?

**Comment by cliffbert** [comment]
Agreed

**Comment by kengdoj** [comment]
Completed.

Preview: https://federalist-78ccea55-7a06-447c-aabf-bd620b207b74.app.cloud.gov/preview/atbcb/icttestingbaseline/nextupdateafter301/10Forms/#105-test-procedure-for-form-has-a-visible-label
