### ISSUE TITLE
Update 7. Sensory Chars advisory tip

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#346]
Update to the Baseline advisory tip to:

-	Content that uses color must have an additional visual cue. Instructions that rely on a sensory characteristic must have an additional visual cue. It is possible to cover both requirements in a single test.

**Comment by kengdoj** [comment]
4/5/22 nextupdateafter301 branch: Update made to 07Sensory.md and ChangeLog3.md.

**Comment by cliffbert** [comment]
I think we discussed [https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics](url) where the example says that color and shape alone still fail. However, I don't recall why we allow (instructions that refer to) combo of color and shape to pass. Could someone re-explain, if that is the case?

**Comment by cliffbert** [comment]
For Sensory, should "color" be added to this list: shape, size, visual location, orientation, or sound?

**Comment by kengdoj** [comment]
Good question @cliffbert!

WCAG 2.0 1.3.3 did not include color in the SC; WCAG 2.1 1.3.3 does:

[2.0: 1.3.3](http://www.w3.org/TR/2008/REC-WCAG20-20081211/#content-structure-separation-understanding) Sensory Characteristics: Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components such as shape, size, visual location, orientation, or sound. (Level A)

[2.1: 1.3.3 Sensory Characteristics](https://www.w3.org/TR/WCAG21/#sensory-characteristics) (Level A): Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components such as shape, **_color_**, size, visual location, orientation, or sound.

**Comment by kengdoj** [comment]
> SC 1.4.4 Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.

- another visual cue required specified by 1.4.4

Is another visual cue acceptable to meet 1.3.3 Sensory Chars?

**Comment by bruce-usab** [comment]
1.3.3 says: do not rely solely on sensory characteristics.

1.4.4 says not only color -- but allows two different visual-only modes.

**Comment by kengdoj** [comment]
Delete this advisory tip.

**Comment by kengdoj** [comment]
From @bruce-usab:

from [2.0 Errata](https://www.w3.org/WAI/WCAG20/errata/#editorial):

11. Success criteria [1.3.3](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#content-structure-separation-understanding) and [1.4.1](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-without-color) each refer to color and the language of the notes confuses the Working Group’s intent. Removing the notes for both and adding color to the list of sensory characteristics in 1.3.3 clarifies the success criteria and preserves the original intent.
