### ISSUE TITLE
5. Changing Content and 4.1.2

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#350]
4.1.2 is applicable to all [user interface components](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html#dfn-user-interface-component) (including but not limited to: form elements, links and components generated by scripts).

Baseline 5. Changing Content test for 4.1.2 must be edited to limit testing to user interface components. Understanding 4.1.2 version 2.1: 

> user interface component - a part of the content that is perceived by users as a single control for a distinct function
> NOTE: Multiple user interface components may be implemented as a single programmatic element. "Components" here is not tied to programming techniques, but rather to what the user perceives as separate controls.
> NOTE: User interface components include form elements and links as well as components generated by scripts.
> NOTE: What is meant by "component" or "user interface component" here is also sometimes called "user interface element".
> An applet has a "control" that can be used to move through content by line or page or random access. Since each of these would need to have a name and be settable independently, they would each be a "user interface component."

**Comment by kengdoj** [comment]
[Understanding 4.2.1 version 2.0 definition](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html#user-interface-componentdef):

> user interface component - a part of the content that is perceived by users as a single control for a distinct function
> Note 1: Multiple user interface components may be implemented as a single programmatic element. Components here is not tied to programming techniques, but rather to what the user perceives as separate controls.
> Note 2: User interface components include form elements and links as well as components generated by scripts.
> Example: An applet has a "control" that can be used to move through content by line or page or random access. Since each of these would need to have a name and be settable independently, they would each be a "user interface component."

This note is new in 2.1 version of definition:
> NOTE: What is meant by "component" or "user interface component" here is also sometimes called "user interface element".

**Comment by kengdoj** [comment]
[Failure 20](https://www.w3.org/WAI/WCAG21/Techniques/failures/F20.html): Failure of Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when changes to non-text content occur. 

This fails 4.1.2, but the non-text content is not a control, i.e., not a user interface component.

Seeking comment from @bruce-usab, please.

**Comment by bruce-usab** [comment]
This is another good example of TT/Baseline close review of WAI materials spotting less-than-great prose.  None of [those examples](https://www.w3.org/WAI/WCAG21/Techniques/failures/F20.html#examples) are UIC so those examples fail 1.1.1 not 4.1.2.

An F20 4.1.2 example would be a button, perhaps a slider, which changes from visually presenting as <q>on</q> to <q>off</q>.  But with HTML5 and WAI-ARIA &mdash; is this sort of button example anything but quaint?

Please be encouraged to files an issue, and maybe a PR.  Or ask me to do so.

**Comment by kengdoj** [comment]
> Or ask me to do so.

Asking @bruce-usab to open the issue/PR for [Failure 20](https://www.w3.org/WAI/WCAG21/Techniques/failures/F20.html).

**Comment by bruce-usab** [comment]
I will use my best judgement, changing as little as possible.

> An F20 4.1.2 example would be a button, perhaps a slider, which changes from visually presenting as on to off with Accessible Name having a static/wrong value.

Can anyone code pen this or what?

**Comment by drewnielson** [comment]
I think we have an example already: 
  * [Test Case](https://section508coordinators.github.io/baselinealignment/testcases/TC05.1-2-fail-1.html)
  * [Sample Code](https://section508coordinators.github.io/baselinealignment/testfiles/TF05/05.1-2-fail-1.html)

**Comment by bruce-usab** [comment]
Thank you @drewnielson &mdash; that is exactly the sort of (bad) model example I was hoping for!

**Comment by kengdoj** [comment]
closed by #377
