### ISSUE TITLE
Forms Page - Not Sure Why the Word AND is Capitalized

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#359]
From ICTTestingBaseline created by [jfc3-dol](https://github.com/jfc3-dol): Section508Coordinators/ICTTestingBaseline#10  

On the Form page ( https://section508coordinators.github.io/ICTTestingBaseline/10Forms.html ), I'm not sure why the word AND is capitalized between the G115 and H49 links? 

Maybe make the text bold instead of capitalized, so people realize there are two links on the line, or maybe if possible, place the second link in a separate list item.

The same applies to the text below.

`<title>` element, AND the `<title>`

**Comment by kengdoj** [comment]
The capitalization of the word "AND" between the two techniques is replicated from the [SC 1.3.1 Sufficient Techniques](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131&currentsidebar=%23col_overview&versions=2.1#info-and-relationships).

Both techniques, when implemented together, would meet the SC.

**Comment by bruce-usab** [comment]
I will take the liberty to suggest following your own style guide.  Historically WAI informative documents have the same tendency as anywhere else to use capitalization for emphasis.  It is not something to emulate.

**Comment by kengdoj** [comment]
Bold will be added for structural emphasis.
