### ISSUE TITLE
Color and lightness

### ISSUE THREAD

**Issue by cliffbert** [atbcb/ICTTestingBaseline#399]
07 Sensory baseline mentions "Displaying content in greyscale may help identify content that uses only color to convey information." but does this adequately address "If content is conveyed through the use of colors that differ not only in their hue, but that also have a significant difference in lightness, then this counts as an additional visual distinction, as long as the difference in relative luminance between the colors leads to a contrast ratio of 3:1 or greater"? https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html

For example, this calendar uses a light gray for the dates in the past. It's use of color (although one might argue the user should know the "extra" info already in this case), but if the ratio between that gray and the darker color for future dates works, it should pass:

![image](https://user-images.githubusercontent.com/30931075/220950032-dc96f3f4-17da-4bbf-9f07-ac947b6b5ff4.png)

**Comment by kengdoj** [comment]
That Advisory Tip ("Displaying content in greyscale may help identify content that uses only color to convey information.") is to help identify applicability, not whether it passes or fails. 

Would you rather it be removed?

**Comment by kengdoj** [comment]
Notes from WG discussion: 

- For text, the 3:1 contrast between the text colors adds to the contrast requirement of each text color against its background. 
- Define a measurable "significant difference in lightness".  
  - Is grey a light black?
  - Is pink a light red?
- Define a measurable difference in hue. 
  - Are grey and black the same hue?
  - Are pink and red the same hue?

**Comment by cliffbert** [comment]
Per discussion, TBD 2.2

**Comment by kengdoj** [comment]
The note for [2.2 Understanding Use of Color](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color) is the same as 2.1's:

> Note
> 
> If content is conveyed through the use of colors that differ not only in their hue, but that also have a significant difference in lightness, then this counts as an additional visual distinction, as long as the difference in relative luminance between the colors leads to a contrast ratio of 3:1 or greater.  For example, a light green and a dark red differ both by color (hue) and by lightness, so they would pass if the contrast ratio is at least 3:1. 

(This has been included in the next update for the Baseline.)

Fun twist: [The colors black, white, and gray are not hues.](https://huckleberryfineart.com/chroma-and-hue-whats-the-difference/)

From the screenshot, the foreground colors (of dates before Feb 16th to the dates after) have a 16:0 contrast ratio using CCA eyedropper. 

- there isn't a failure of 1.4.1 Use of Color
- the dates before Feb 16th fail 1.4.3 Contrast (Minimum)

**Comment by kengdoj** [comment]
@cliffbert - please close this issue if resolved?
