### ISSUE TITLE
Decorative (?) Images Conflict

### ISSUE THREAD

**Issue by cliffbert** [atbcb/ICTTestingBaseline#409]
Currently TT says “All images which convey information should be considered meaningful images.” Only super-abstract stuff (and bullets) are exempt. Pro: all users are aware of and can refer to images on the page. Con: may be redundant info.

But [baseline ](https://github.com/atbcb/ICTTestingBaseline/blob/main/_baselines/06Images.md)says “Equivalent descriptions for an image within page text could allow an image to be considered decorative. However, this does not necessitate removal of any accessible text attributes from the image.” This implies that a meaningful image could be considered decorative and not need alt text if described nearby. Pro: no redundancy. Con: not all users aware of or can refer to some images.

Which should we require? Or do we leave it per WCAG’s “Whether to treat an image as decorative or informative is a judgment that only the author can make, based on the reason for including the image on the page”?

**Comment by kengdoj** [comment]
I think we should remove “Equivalent descriptions for an image within page text could allow an image to be considered decorative. However, this does not necessitate removal of any accessible text attributes from the image.”. It is a remnant of the old Baseline.

The definition of decorative from [WCAG SC 1.1.1](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131%2C253&currentsidebar=%23col_overview&levels=aaa#non-text-content) is:

> •	Decoration, Formatting, Invisible: If non-text content is pure decoration, is used only for visual formatting, or is not presented to users, then it is implemented in a way that it can be ignored by assistive technology.



With that very narrow definition of PURE decoration, most of those things that we have considered decorative (like icons of binoculars, handshake, etc.) would not be decoration since they have some relationship to the content.

**Comment by kengdoj** [comment]
[definition of pure decoration](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html#dfn-pure-decoration):

> serving only an aesthetic purpose, providing no information, and having no functionality
> 
> Note
> Text is only purely decorative if the words can be rearranged or substituted without changing their purpose.
> 
> The cover page of a dictionary has random words in very light text in the background.

**Comment by bruce-usab** [comment]
@cliffbert can you provide link to that WAI guidance excerpt?

Here are two authoritative (but not normative) examples using null alt for not-obviously only decorative:
- https://www.w3.org/WAI/tutorials/images/decorative/#example-3-image-with-adjacent-text-alternative
- https://www.w3.org/WAI/tutorials/images/decorative/#example-4-image-used-for-ambiance-eye-candy

In a similar vein, WebAIM has long argued that “Smiling Lady” images should use null alt, see [Alt Text Blunders](https://webaim.org/articles/gonewild/#alttext).

**Comment by kengdoj** [comment]
@cliffbert, would you please add the text from the May 2 group discussion?

**Comment by cliffbert** [comment]
I'm writing up a summary of this - is this the right idea?

Image with blank alt text: supposed to be decorative. Check if decorative.

Image with non-blank alt text: Supposed to be meaningful. Check if meaningful.

**Comment by kengdoj** [comment]
Update 18.1 Background images with similar change.
