### ISSUE TITLE
Identifying Lists

### ISSUE THREAD

**Issue by cliffbert** [atbcb/ICTTestingBaseline#420]
https://github.com/atbcb/ICTTestingBaseline/blob/c9c0661d7fce430eecfb86724a796711153c1f66/_baselines/13Structure.md?plain=1#L80C23-L80C23

Currently TT says ignore navigational framework: "•	Exclude menus or other elements that are part of the page’s navigational framework from this test. Developers might use list elements to create grouped navigational items, such as menus, submenus, lists of navigation links, breadcrumbs, etc. while styling them to remove bullets or numbering and orienting the lists horizontally instead of vertically. If these navigational elements are part of the page’s navigational framework, separate from the main content, they should not be considered visually apparent lists for this test and should be excluded since we cannot require that all such items be coded as lists. However, any lists which are part of the main content should be included."

However, what if lists of links etc. are bulleted or numbered? Should they be included?

For example, if we see this list of links on the right of a page: 

![image](https://github.com/atbcb/ICTTestingBaseline/assets/30931075/da84fd3a-d004-427c-8b27-beef2daa8b4a)

or this list below the main content, in a separate section:

![image](https://github.com/atbcb/ICTTestingBaseline/assets/30931075/8d336255-fb12-4604-b271-50e7ee65052a)

Should we include ANY content that has bullets (numbered or not) since they look like lists, regardless of navigation-ishness, but not lists without bullets/numbers? Else that may lead to requiring TOC or links like these be coded as lists:

![image](https://github.com/atbcb/ICTTestingBaseline/assets/30931075/0ecbfd92-f07a-4888-af94-b4b2d5a23b6a)

**Comment by cliffbert** [comment]
Proposed update to TT (emphasis added to show updates):

**Lists**
**Identify Content**
Identify all visually apparent lists on the page. 

Note: 
•	Keep in mind that this test only applies to visually apparent lists, not programmatic lists identified by ANDI. As such, ANDI should not be used to identify lists to be tested; ANDI should only be used to evaluate whether visually apparent lists are properly coded.
•	Menus or other elements that are part of the page’s navigational framework **should normally be excluded** from this test. Developers might use list elements to create grouped navigational items, such as menus, submenus, lists of navigation links, site navigation, page navigation, breadcrumbs, etc. while styling them to remove bullets or numbering and orienting the lists horizontally instead of vertically. If these navigational elements are part of the page’s navigational framework, separate from the main content, they should not be considered visually apparent lists for this test and should be excluded since we cannot require that all such items be coded as lists. **However, any such elements which appear to be numbered or bulleted lists** should be included in testing.
•	Any lists which are part of the main content should be included.

Question: is this adequate to exclude the indicated unbulleted list from testing (assuming it should be excluded since it is 1. not part of main content "prose-like" section, and 2. not "site- or page-wide" navigational element)?

![image](https://github.com/atbcb/ICTTestingBaseline/assets/30931075/10c39c58-c098-4b9c-8cd8-eb4d24853b65)

**Comment by cliffbert** [comment]
Suggestion:

For TT exam, make it really clear - add bullets for list to be tested.

For real life - if not clearly navigational element as listed, tester may decide to test something that looks like a list. Devs may respond that they intended it to be considered navigational (or not, and remediate).

**Comment by bruce-usab** [comment]
Looks good to me, I think it is great that TT has concept of "visually apparent list", and something I hope to (eventually) borrow for [Understanding](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships).  But editorial nitpick follows.

Current above:
> should normally be excluded

Suggest:
> should usually be excluded

Rationale:  "usual" refers to frequency.  The word "normal" is a value judgement and it's too often used to contrast things done to improve accessibility.

**Comment by cliffbert** [comment]
> Looks good to me, I think it is great that TT has concept of "visually apparent list", and something I hope to (eventually) borrow for [Understanding](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships). Regardless editorial nitpick follows...
> 
> Current above:
> 
> > should normally be excluded
> 
> Suggest:
> 
> > should usually be excluded
> 
> Rationale: "usual" refers to frequency. The word "normal" is a value judgement and it's too often used to contrast things done to improve accessibility.

Thanks, Bruce! Edited per your suggestion.

**Comment by kengdoj** [comment]
Exclude menus has been added.
