### ISSUE TITLE
What is threshold for adequately describes important visual content?

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/ICTTestingBaseline#423]
[17.5 Audio Description (Prerecorded)](https://ictbaseline.access-board.gov/17SyncMedia/#175-test-procedure-for-audio-description-prerecorded) asks if the narration **adequately** describes important visual content?

If a video features continuous narration from start to finish, but the speakers/presenters do not do a _great_ job describing their visuals, is that a failure against  [17.5 Audio Description (Prerecorded)](https://federalist-78ccea55-7a06-447c-aabf-bd620b207b74.sites.pages.cloud.gov/preview/atbcb/icttestingbaseline/nextupdateafter301/17SyncMedia/#175-test-procedure-for-audio-description-prerecorded)?

I am asking because:
1. Definitionally/historically/traditionally, audio description is limited to gaps in dialog.
2. If there are not gaps in dialog, there is not an opportunity for additional narration.
3. There is a current [debate for WCAG](https://github.com/w3c/wcag/issues/3254) if lack of gaps in dialog means that SC 1.2.5 is an automatically failure?
4. It is good to maintain parity between WCAG Understanding and ICT Baseline for Web.

Does a less-than-great audio track, where there is nothing but "talking heads" mean that the video needs to be re-recorded?  Is a technique like [extended audio description](https://www.w3.org/WAI/WCAG20/Techniques/general/G8.html) **required** for such situations?

**Comment by bruce-usab** [comment]
Ping to @cliffbert , my fellow ruminator.

**Comment by cliffbert** [comment]
To me "adequately" means "good enough," which means it includes any important visual information (and deciding that may be up for grabs).

#3 cannot be an automatic failure unless we require freezing of the media - although this may be a solution, if the player offers this as an **option**, per extended AD. Otherwise this will mean inserting AD into other, nearby gaps instead.

**Comment by kengdoj** [comment]
17.5 test step 2: 

> Check that the **audio (with audio descriptions enabled)** adequately describes important visual content in the media, including information about actions, characters, scene changes, on-screen text, and other visual content. 

The audio description definition does not require that the narration be synchronized with the visual information as it appears. AD can be added at the beginning or end of the video, when a gap is likely to exist. And, if it's a separate AD track, there should be no problem having AD at the beginning and end, if there's constant dialog in between.

> audio description
> narration added to the soundtrack to describe important visual details that cannot be understood from the main soundtrack alone
