### ISSUE TITLE
Menu level "Same or higher"?

### ISSUE THREAD

**Issue by cliffbert** [atbcb/ICTTestingBaseline#424]
https://github.com/atbcb/ICTTestingBaseline/blob/c9c0661d7fce430eecfb86724a796711153c1f66/_baselines/17SyncMedia.md?plain=1#L60C91-L60C91

Should we explicitly state that 17.2 and 17.3 allow for the controls to be at the same **or higher** menu level as volume/program selection?

**Comment by KMSOC** [comment]
Defer to USAB for official guidance, but the standard says "same level" which does not seem to suggest a higher menu level.

**Comment by kengdoj** [comment]
The requirements below state "same". 

I wouldn't object to a test process that said "or higher", as it would be going beyond requirements, but not in the Baseline. One would assume that volume or program selection controls are pretty high in the menu level.


> 503.4.1 Caption Controls
> Where user controls are provided for volume adjustment, ICT shall provide user controls for the selection of captions at the same menu level as the user controls for volume or program selection.
> 
> 503.4.2 Audio Description Controls
> Where user controls are provided for program selection, ICT shall provide user controls for the selection of audio descriptions at the same menu level as the user controls for volume or program selection.

**Comment by cliffbert** [comment]
OK, will stay at "same". Thanks!

**Comment by cliffbert** [comment]
Correction: TT will allow for higher level.
