### ISSUE TITLE
Baseline for tables tests for headers attribute, which Chromium browsers do not support

### ISSUE THREAD

**Issue by jameslpetersen** [atbcb/ICTTestingBaseline#448]
The [tables baseline](https://ictbaseline.access-board.gov/12DataTables/) tests for the presence of the [headers attribute](https://ictbaseline.access-board.gov/12DataTables/#test-instructions). Chromium (the browser engine for Blink and Chrome) [does not support that attribute](https://bugs.chromium.org/p/chromium/issues/detail?id=1081201); it's currently not a reliable technique for making tables accessible. The presence of the headers attribute is actually an indication that a table is **not accessible** to screen reader users on Chrome/Blink.

 This relates to a broader question about the baseline. What OS/browser/reader combos should work with the baseline tests? Just VoiceOver/Safari and Firefox/NVDA? Or do the tests need to work with other combos?

**Comment by kengdoj** [comment]
Hi @jameslpetersen, thanks for clarifying.

I checked again and found that NVDA did not announce the headers in either table correctly. For Example 2, it announced both Paris and Rome, when it should have only announced Rome. 

The lack of NVDA support for sufficient technique [H43: Using id and headers attributes to associate data cells with header cells in data tables](https://www.w3.org/WAI/WCAG22/Techniques/html/H43) and a user's experience with this particular example is described in an [NVDA issue](https://github.com/nvaccess/nvda/issues/14373). 

When NVDA addresses this issue, it should read tables with headers/id correctly. (I checked Example 1 and Example 2 with JAWS, and it announced the correct headers for both tables.)

**Comment by jameslpetersen** [comment]
Hi, @kengdoj,

I noticed that you closed this issue. As far as I know, Chromium browsers still do not support the headers attribute for table cells and Google/Microsoft have shown no interest in fixing the bug. [This post](https://adrianroselli.com/2022/01/accessible-cart-tables.html) explains how the bug affects JAWS and NVDA.
