### ISSUE TITLE
Questions about what some things in the Entity Summary Report mean

### ISSUE THREAD

**Issue by stephanieosan** [atbcb/ICTTestingBaseline#452]
Hi there! I'm the product management lead at the Consumer Financial Protection Bureau. I'm excited to check out your report on our agency, but there are a few aspects of it that I don't understand. 

1) What does "ICT" stand for?
2) What is the difference between "top viewed" pages and those evaluated?
3) For the purposes of your review, how did you determine which pages were top viewed?

Thanks!
Stephanie

**Comment by kengdoj** [comment]
Hi Stephanie,

This ICT Testing Baseline group isn't behind the [508 Assessment Report](https://www.section508.gov/manage/section-508-assessment/2023/message-from-gsa-administrator/). I'd recommend submitting your questions about the report to section.508@gsa.gov. 

As we are an interagency working group, we also weren't one of the reporting entities. But I can tell you that ICT is Information Communication Technology, and if you need further information about the Section 508 Standards, please email 508@access-board.gov.

**Comment by drewnielson** [comment]
Hi Stephanie,

While the US Access Board and GSA collaborate on the content in this repository and we also collaborated on the Governmentwide Section 508 Assessment, this repository is quite separate from the assessment. I would suggest that this repository's issue log is likely not the best forum to engage in questions about the assessment. Nevertheless, I am happy to answer your questions while I am here.
  1. **Q**: What does "ICT" stand for? **A**: ICT stands for Information and Communication Technology. This term is defined in its first use in the report, but easy to miss if you're not reading from the beginning of the assessment/report. You can also refer to the assessment's [Terms and Definitions](https://www.section508.gov/manage/section-508-assessment/2023/appendix-a-terms/) and/or the Assessment's [Acronyms List](https://www.section508.gov/manage/section-508-assessment/2023/appendix-a-acronyms/) for other unfamiliar terms used in the document. 
  2. **Q**: What is the difference between "top viewed" pages and those evaluated? **A**: In the [assessment criteria for conformance metrics](https://www.section508.gov/manage/section-508-assessment/criteria-11/), in questions [70](https://www.section508.gov/manage/section-508-assessment/criteria-11/#q70)-[75](https://www.section508.gov/manage/section-508-assessment/criteria-11/#q75), agencies were asked to report how many web pages they evaluated for Section 508 conformance and by what methods. In addition to any overall evaluation, agencies were also asked to conduct comprehensive testing (which must include manual inspection) for the top ten viewed web pages in question [78](https://www.section508.gov/manage/section-508-assessment/criteria-11/#q78) (for internal intranet pages) and question [79](https://www.section508.gov/manage/section-508-assessment/criteria-11/#q79) (for public internet pages). 
  3. **Q**: For the purposes of your review, how did you determine which pages were top viewed? **A**: The content in ["Understanding Question 62"](https://www.section508.gov/manage/section-508-assessment/criteria-11/#u62) and ["Understanding Question 79"](https://www.section508.gov/manage/section-508-assessment/criteria-11/#u79) provides some guidance for agencies to help determine the top viewed we pages. However, the instructions are not definitive as an agency's approach for determining top viewed pages could depend on the agency's publishing platform and analytics tools. Your [Section 508 Program Manager](https://www.section508.gov/tools/program-manager-listing/#consumer-financial-protection-bureau-cfpb) should be able to provide a more definitive answer for how your agency determined its top 10 most viewed pages.

Please direct any additional questions about the assessment to our mailbox at section.508@gsa.gov. Alternatively, please reach out to your Section 508 PM for questions about your agency's specific responses to that assessment criteria.
