### ISSUE TITLE
Acceptable Pass for 3.3.4 - one-page form

### ISSUE THREAD

**Issue by cliffbert** [atbcb/ICTTestingBaseline#466]
One of the Techniques pages for 3.3.4, [G98: Providing the ability for the user to review and correct answers before submitting | Techniques for WCAG 2.0 (w3.org)](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G98) says that “On a simple, 1-page form this is easy because the user can review the form before submitting.” This seems to imply that if a form is only in one page it already meets the criteria of letting the user review their input before submitting the form, and nothing else is required to pass this SC.  

This page also seems to restrict application of 3.3.4 to multi-step forms, although this is not mentioned on the [Understanding Success Criterion 3.3.4 | Understanding WCAG 2.0 (w3.org)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-reversible.html) 

Is this the understanding that we are adopting or are we requiring additional confirmation such as a "Reviewed" checkbox? If so, baseline tests for 3.3.4 should apply only to multi-step forms.

**Comment by cliffbert** [comment]
Already in advisory tip in new baseline: https://federalist-78ccea55-7a06-447c-aabf-bd620b207b74.sites.pages.cloud.gov/preview/atbcb/icttestingbaseline/nextupdateafter301/10Forms/#10g-test-procedure-for-error-prevention-legal-financial-data

**Comment by bruce-usab** [comment]
One thing to be aware of is that the W3C informative documents are _slowly_ being refreshed.  Look for the URL to contain WAI (and _not_ TR).  For G98, it looks to me like the text unchanged, and only the formatting is improved.
- https://www.w3.org/WAI/WCAG22/Techniques/general/G98

The improvements with current [Understanding SC 3.3.4](https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-legal-financial-data.html) are more than cosmetic.
